name: Python Application Deployment

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

<<<<<<< HEAD
=======
<<<<<<< HEAD
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ inputs.image_name }}:latest
=======
>>>>>>> ecbff7b (correction)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GHR_TOKEN }}
<<<<<<< HEAD
=======
>>>>>>> parent of 61805a1 (test)
>>>>>>> ecbff7b (correction)

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest

  deploy-to-aks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: 'Deploy to Azure Kubernetes Service'
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: dev-k8s
        resource-group: dev-k8s-rg

    - name: 'Set Image Name and Deploy'
      run: |
        kubectl set image deployment/python-hello-world python-hello-world=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:latest
