name: Test Secrets Visibility

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check GH_USERNAME Secret
        run: |
          echo "GH_USERNAME is ${{ secrets.GH_USERNAME }}"
      
      - name: Check GHR_TOKEN Secret
        run: |
          echo "GHR_TOKEN is ${{ secrets.GHR_TOKEN }}"

      - name: Check AZURE_CREDENTIALS Secret
        run: |
          echo "AZURE_CREDENTIALS is ${{ secrets.AZURE_CREDENTIALS }}"
