name: Test Secrets Visibility

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check GHR_USERNAME Secret
        run: |
          echo "GHR_USERNAME is ${{ secrets.GHR_USERNAME }}"
      
      - name: Check GHR_PASSWORD Secret
        run: |
          echo "GHR_PASSWORD is ${{ secrets.GHR_PASSWORD }}"

      - name: Check AZURE_CREDENTIALS Secret
        run: |
          echo "AZURE_CREDENTIALS is ${{ secrets.AZURE_CREDENTIALS }}"
